### ISSUE TITLE
[FEATURE] Reconsider how Master AF affects VAC audio levels

### ISSUE THREAD

**Issue by w-u-2-o** [sjk7/Thetis-2.9.0#1]
Hello Steve,

First off, thanks for the effort you are putting into this. And, while not a dev myself, it's certainly well known what a nasty bowl of spaghetti the main console UI code is.

Back on point...

The change to make Master AF affect VAC1 is potentially disruptive to a lot of people.

Disclaimer: I'm strictly VAC audio here, so anything that makes VAC1 act more like the "normal" CODEC audio feed is great for me, but...

The design intent and assumptions of the original developers, going way back to early openHPSDR versions of PowerSDR, was that listening was going to be done exclusively via the CODEC output of the Hermes, with only digi software connected via VAC. This allows RX1 and RX2 AF to be run up to 100%, the equivalent of digital line out levels for digi app's, while Master AF could be adjusted to a comfortable listening volume. I suspect a lot of folks continue to operate in this manner. Adding Master AF control over VAC1 output levels is going to screw that up unless it's made to be a user selectable option.

A better way to do this would be to have a user selectable option in VAC1 to select either the existing VAC1 RX1 audio stream, or the CODEC audio stream. This way the folks doing it the "old school way" are not screwed up, and those who are relying 100% on VAC audio can get the CODEC stream with all UI controls and RX1 and RX2 mixed. Indeed, it would be even better if both VAC1 and VAC2 had this option and the VAC UI offered three options: CODEC, RX1 and RX2. That way the user could mix/match VAC1 and VAC2 as required.

Thanks again,

Scott/wu2o

**Comment by sjk7** [comment]
Hello,
I am confused. How does it impact on users just using the software the old school way?

(I have never used any SDR with a built in audio system myself).

I mean -- for those users, currently how do they use the software (presumably digital modes only) -- or, more precisely, what does the master AF control do for them that is fcked up by having it adjust the VAC rx and monitor level?

Thanks,
Steve

**Comment by sjk7** [comment]
Oh wait, I see what you are saying. The master AF control used to control something _else_ that made it do zero for the HL2?

**Comment by w-u-2-o** [comment]
Hi Steve,

Yes, exactly. The HL2 is a different hardware platform in many ways. I need to get a little smarter on that in order to understand how those changes might be informing your ideas for changes to Thetis. I will be therefore studying the HL2 schematics over the next few days.

However, it sounds like (ha, a pun!) that the HL2 does not include an audio CODEC IC like the original Hermes does (and all of its Apache Labs derivates do). The original designers of the Hermes believed that it would be necessary to keep the audio hardware in the same clock domain as the ADC & DAC, hence the inclusion of the audio CODEC on the board, but of course that's not true. They also wanted a more traditional look & feel for the operator, i.e. a way for them to plug speakers, mic's and headphones into the "box", not the PC.

As a result of this, there is a separate audio stream in Thetis (and PowerSDR mRX before it) that I refer to as the "CODEC" stream. This consists of RX1, RX2, RX1 subreceiver and MON audio all mixed together in accordance with the main console UI controls. Meanwhile the VAC1 audio stream only consists of RX1, RX1 sub and MON, and VAC2 only consists of the RX2 audio stream.

In addition, consider that on Hermes and derivative (not HL2 apparently), that any audio to/from this CODEC is routed up/down the Ethernet to/from Thetis for processing. Another way to look at it is that this CODEC and associated hardware comprises a separate, custom "sound card" located on the Hermes (and derivative) board.

73,

Scott

**Comment by sjk7** [comment]
Just uploading the 64 and 32 bit msi files to address this right now. Give it a few minutes and please try it out. There is a checkbox for this (gawd) on VAC1 setup.

**Comment by w-u-2-o** [comment]
Hi Steve,

Thanks! Very busy the rest of this week, little time for radio, but I should be able to test this over the weekend.

Will post back here then.

Cheers!

Scott

**Comment by sjk7** [comment]
cool. thanks

**Comment by RdWing** [comment]
For what it's worth, I 'm with @sjk7 on this one. Much prefer 100% VAC operation with all controls affecting VAC by default.

**Comment by sjk7** [comment]
> For what it's worth, I 'm with @sjk7 on this one. Much prefer 100% VAC operation with all controls affecting VAC by default.

If you select HL2 as the radio, this is what you get. If not, there is a new tickbox on the top of the VAC1 tab to enable it.

**Comment by w-u-2-o** [comment]
My apologies for being late to the party. I was unavoidably detained by life ;-)

I have, finally, caught up and got 2.9.0.19 installed and of course this function works as designed and will allow legacy behavior for users as required.

Cheers!

Scott
