### ISSUE TITLE
Setup -> Transmit -> Export Current Profile and Import TX Profile should behave as in 2.9.0.8

### ISSUE THREAD

**Issue by jeffreydoran** [sjk7/Thetis-2.9.0#12]
**Is your feature request related to a problem? Please describe.**

As it applies to Setup -> Transmit 

This feature request is to have Export Current Profile behave exactly like 2.9.0.8, that is export the current Transmit Audio characteristics to a filename that is the same as the Transmit Profile name. 

The Transmit Profile items are highlighted by checking "Highlight TX Profile Save Items"

And then is each successive save, append and increment a NUMBER to the profile name so as all previous TX audio characteristics are saved, in a series of files.

**Describe the solution you'd like**

Would like to Export and Import TRANSMIT PROFILES exactly like version 2.9.0.8

73,

Jeff NJ2US

**Comment by sjk7** [comment]
How do you import them, thou? I don't see an option to import one in 2.9.0.8 ?

Steve
