### ISSUE TITLE
[BUG] After taking a Quick Record, radio boots and starts playing the recording.

### ISSUE THREAD

**Issue by RdWing** [sjk7/Thetis-2.9.0#14]
2.9.0.15 x64, W11, 7000 DLE Mk2.5

During the previous radio session, I used the quick record and playback buttons on the main interface to record/playback a station over the air, then closed Thetis as normal.

The next time I started Thetis, after hitting the power button the radio immediately started playing the file, and it showed up on the waterfall/panadapter as a playback does.

The Play button did not indicate it was actually playing a file, but the Wave menu showed the Quick Play button highlighted yellow.

To try and remediate, I went to %appdata\Roaming\OpenHPSDR\Thetis-x64 and renamed SDRQuickAudio.wav to something else and tried to boot Thetis. I then received the following error.

![image](https://user-images.githubusercontent.com/19214916/232723208-bd9bf52c-26f4-41e1-ab4d-8e6471aba086.png)

After accepting the error, Thetis booted. However, the error sticks around every time now. I tried creating a new recording and now Thetis plays the recording upon start every time.

This behavior is new to me on this fork and has not been seen before on any other version.

**Comment by sjk7** [comment]
Thanks. You know, I can't even get wav playback to work at all. Its just a distorted mess. Is there anything I can do (I bet there is a tickbox somewhere ;-) to fix it?
Steve

**Comment by sjk7** [comment]
Hello! Gonna need some more help with this. I cannot reproduce it :-(
Here's what I did:

Radio on 40m: recorded some German using the REC button.
When I'd had enough, I played it back to myself. OK.
Closed the app.

Reopened Thetis. Powered up. Worked as normal. Note the recording was not available for playback in the new Thetis session. I don't know if this is normal behaviour or not. (IOW: the play button did nothing in the new session, even though the QuickRecord.wav is still there)

Then I did the same thing once more, but this time played back in MOX mode (I am assuming that's what you actually did). But again I restarted it, and there was no weird behaviour. Note that to get it to play in MOX here on the HL2, I had to tick the box on the audio tab 'bypass VAC for recording playback'

I don't know if any of this means anything to you? Trouble is, if I cannot replicate it, I cannot fix it :-(

Steve

**Comment by sjk7** [comment]
Ok, spent some considerable time looking for this and the only thing I can see that would logically cause this is database corruption. I definitely cannot replicate here. In fact that whole Wave control is a bit messy.

Can you confirm that this does not happen with a known, good database? Does your wave control ever save the items in the playlist? Mine does not seem to, and perhaps this is why I cannot replicate. Gonna close for now, pending more feedback.

No problem in re-opening this ticket, depending on the feedback I recieve  from you.

Thanks!

Steve

**Comment by RdWing** [comment]
Wave control never saved stuff in the playlist. I dug into the database xml where I found the following keys.

I had previously used the wav recorder to take some I/Q recordings, maybe its related, not sure. Anyway. I ripped out the following from my database and the problem has gone away.

```
           <xs:element name="WaveOptions">
             <xs:complexType>
               <xs:sequence>
                 <xs:element name="Key" type="xs:string" />
                 <xs:element name="Value" type="xs:string" minOccurs="0" />
               </xs:sequence>
             </xs:complexType>
           </xs:element>
```
```
  <WaveOptions>
    <Key>createBoxTS</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>TXIDBoxTS</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>chkBoxMP3</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>chkQuickAudioFolder</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>chkQuickPlay</Key>
    <Value>True</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>chkQuickRec</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>udPreamp</Key>
    <Value>0</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>checkBoxRandom</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>checkBoxLoop</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>checkBoxRecord</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>txtCurrentFile</Key>
    <Value />
  </WaveOptions>
  <WaveOptions>
    <Key>checkBoxPause</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>checkBoxPlay</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>Top</Key>
    <Value>986</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>Left</Key>
    <Value>-2158</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>Width</Key>
    <Value>432</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>Height</Key>
    <Value>508</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>udWaveDitherBits</Key>
    <Value>0.8</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>chkWaveDither</Key>
    <Value>True</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>radBitDepth8PCM</Key>
    <Value>True</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>radBitDepth16PCM</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>radBitDepth24PCM</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>radBitDepth32PCM</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>radBitDepthIEEE</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>comboSampleRate</Key>
    <Value>48000</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>radTXPostProcessed</Key>
    <Value>False</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>radTXPreProcessed</Key>
    <Value>True</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>radRXPostProcessed</Key>
    <Value>True</Value>
  </WaveOptions>
  <WaveOptions>
    <Key>radRXPreProcessed</Key>
    <Value>False</Value>
  </WaveOptions>
  ```

**Comment by sjk7** [comment]
Thanks for feedback. I'm gonna blame

  <WaveOptions>
    <Key>chkQuickPlay</Key>
    <Value>True</Value>
  </WaveOptions>

That one! This saving of every control's state in the form is a bit of a PITA sometimes ;-)
