### ISSUE TITLE
[BUG] 192K sample rate is the highest now available for 7000DLE on .17

### ISSUE THREAD

**Issue by NC3Z** [sjk7/Thetis-2.9.0#15]
192K sample rate is the highest now available for 7000DLE

Before .17 was able to select 384K up to 1536K, now only 48,96 or 192K are the only options.

 - OS: Win 11

**Comment by NC3Z** [comment]
I did try the new suggestions on missing sample rate with no joy. But I did the unthinkable and selected Auto and let it select P2 it's self and now I have the higher sample rates. .17 will then autodetect and select P2, upon restart I loose the higher sample rates again. To regain them I must toggle off P2 (to either P1 or Auto) and then back again to be able to get the rates back.

**Comment by jeffreydoran** [comment]
I am seeing the same Sample Rate issue as NC3Z

NJ2US

**Comment by SM3PZG** [comment]
Exactly the same for me too. 

SM3PZG

**Comment by DH1KLM** [comment]
All P2 sample rates work except 384k, which is missing from the list.
The set sample rate is not saved and after a restart it is 192k again.

![missing](https://user-images.githubusercontent.com/27503182/232802937-fce2160b-21cd-4f84-b472-bad3e29d3b69.JPG)

**Comment by rsaue** [comment]
Using ANAN-200D with protocol2 now shows 192 000 as the highest sample rate on xx.16. Was not so on earlier test versions.  I compiled from master-repository updated this morning.  73 de LB2EG Richard

**Comment by sjk7** [comment]
OK, I have someone with a 100D, so this is easily fixable

Steve

**Comment by sjk7** [comment]
> All P2 sample rates work except 384k, which is missing from the list. The set sample rate is not saved and after a restart it is 192k again.
> 
> ![missing](https://user-images.githubusercontent.com/27503182/232802937-fce2160b-21cd-4f84-b472-bad3e29d3b69.JPG)

384000 -- I meant to take it out for HL2, not for everyone!

Steve

**Comment by W1AEX** [comment]
Can confirm the other reports regarding missing sampling rates. Running v2.9.0.17 with a 200D. If I toggle the protocol selection from protocol 2 to protocol 1f and then back to protocol 2 everything except 384000 is available. I really like the Master volume option for VAC, nicely done!    73,  Rob W1AEX

**Comment by sjk7** [comment]
@W1AEX @rsaue @DH1KLM @jeffreydoran @NC3Z  OK, should be fixed in fresh upload. It is available now. Note this is the only issue I addressed in this revision, and I could do with some feedback as to whether or not things are working as they should right now.

**Comment by rsaue** [comment]
xx.18 compiled and installed in my setup with ANAN-200D. 

All good !

Thanks!

73 de LB2EG Richard

**Comment by DD8JM** [comment]
Great, everything is working again thanks!

Greeting Joerg, DD8JM

Thetis Version 2.9.0.18 / Red Pitaya 16bit Protokoll 2 / Radio Model ANAN 100D

**Comment by W1AEX** [comment]
Steve - Confirming that v2.9.0.18 shows all sampling rates correctly with protocol 2 selected. Additionally, the selection is persistent when Thetis is shut down and then restarted. Looks great here!  73, de Rob W1AEX

**Comment by sjk7** [comment]
Cool! Thanks for feedback, everyone. I guess I can close this one now. It's awkward because I only have a HL2 here. :-(

**Comment by NC3Z** [comment]
@sjk7 Sample rate issue fixed on 7000DLE. Also using it on a TRX-Duo which is like the Hermes and has no onboard codec, Master  AF for the VAC is very helpful.
