### ISSUE TITLE
No data in Mode Data form[BUG]

### ISSUE THREAD

**Issue by va7qi** [sjk7/Thetis-2.9.0#18]
Using 2.9.0.18 and Protocol 2.
When pressing the Mode Data button on Andromeda a blank ModeDependendentSettingsForm shows up, except that it has the Close button.
The issue was 

**Expected behaviour**
Thetis prior to .8 showed data in the form.  Both CW and SSB has been checked.

**Desktop (please complete the following information):**
 - Windows 10 Home with the latest patches.

**Additional context**

73 de va7qi,        ....Erik.

**Comment by sjk7** [comment]
Hello @va7qi 
Thanks for the feedback. I don't even know what this thing is! If it is something we expect to work with an HL2 or an ANAN-100, we (my friend and I) can take a look. Is this something we can check with either a Hermes-Lite 2 or an ANAN-100?

Thanks

Steve

**Comment by sjk7** [comment]
Hi again,

It is this we are talking about:

![mode](https://user-images.githubusercontent.com/24289173/233055859-3aff2032-c36b-4304-8d89-fe88f86a6325.jpg)

If so, seems to work here. Was it a one-time thing, or is it permanently broken @ your end?

**Comment by sjk7** [comment]
Hi,

I found what you are talking about, but this may be a work in progress on Richie's part as it is exactly the same in the version I 'inherited'. I will try to fix if I can, but I doubt I can do much if the code does not exist yet:

![MDS](https://user-images.githubusercontent.com/24289173/233060862-ea273c40-a92c-491c-ad79-bae948b26307.jpg)

Please note that is on Richie's version, and it is not something I have changed.

**Comment by sjk7** [comment]
This is related to:
https://github.com/ramdor/Thetis-2.9.0/issues/90

Pretty sure I can fix. Whether or not it breaks something else, who knows? :-)

**Comment by DH1KLM** [comment]
Just compiled the fix. Changed to collapse and clicked "Mode settings form". The form poped up, I closed it and switched UI back to normal view. And it looks like this.
![1](https://user-images.githubusercontent.com/27503182/233084013-dc749213-9c68-4505-bdaf-177851a0928d.JPG)

After Thetis restart all is back to normal.

**Comment by sjk7** [comment]
@DH1KLM

Hi, this is fixed but only in revision 19+. I will upload the executable tonight or tomorrow. I'm pretty sure its OK, now:

![v19](https://user-images.githubusercontent.com/24289173/233192570-b13c8941-63c6-4661-8106-4ec091e66629.jpg)

There is some really janky stuff in this mode: for example I have seen unwanted buttons popping up all over the place.

**Comment by sjk7** [comment]
Hi! I just uploaded the executable containing the fix:
https://github.com/sjk7/Thetis-2.9.0/releases/download/v2.9.0.4/Thetis-v2.9.0.x64.msi

**Comment by va7qi** [comment]
Hi Steve,

I installed 0.19 this afternoon PDT and it works perfectly.  Thanks!

73 de va7qi,                ....Erik.


------ Original Message ------
From "sjk7" ***@***.***>
To "sjk7/Thetis-2.9.0" ***@***.***>
Cc "va7qi" ***@***.***>; "Mention" ***@***.***>
Date 2023-04-19 13:36:19
Subject Re: [sjk7/Thetis-2.9.0] No data in Mode Data form[BUG] (Issue 
#18)
