### ISSUE TITLE
Has anything changed regarding PTT/OC delays?

### ISSUE THREAD

**Issue by RdWing** [sjk7/Thetis-2.9.0#19]
I have recently started experiencing a weird delay, when I let off my foot switch connected to PTT IN, there is sometimes a delay from the OC PIN 7 deasserting.
I use Open Collector PIN 7 to key an amplifier, and it's just behaving strangely. Just a few tens of ms delay. Occasionally the issue happens when keying down too.

![image](https://user-images.githubusercontent.com/19214916/232970316-0be3c98a-affd-44f8-9767-f2e776fcb4aa.png)

**Comment by sjk7** [comment]
No, I don't use this and have not therefore changed anything here. It's 1% possible that some other change has affected it. Very unlikely though. When I get 5 mins, I will look at the code and see what actually fires it off and if anything is holding it up.

**Comment by RdWing** [comment]
I am quite certain but to be really sure I will roll back to an older (Richie) version and test today, expect more to come later.

**Comment by sjk7** [comment]
Hello,
Did you find anything tangible?

Steve

**Comment by sjk7** [comment]
I think what I need is to actually set up some hardware like a foot switch, etc. Any chance you can baby-steps me a video like the other one?

Steve

**Comment by RdWing** [comment]
Hi, yes, I've been a little busy but I will record something in the next couple days. No worries.

**Comment by sjk7** [comment]
> Hi, yes, I've been a little busy but I will record something in the next couple days. No worries. Also got a friend that got an HL2 recently so will test there also.

That will be useful as it's what I have. If you can replicate on there, then great, I will be able to at least see what thread services it. Something must be spinning, waiting for the input from the foot switch to come in, and I cannot presently identify which thread does that. Maybe Richie knows?

Steve

**Comment by RdWing** [comment]
https://youtu.be/PgX2QRoCJXY
Here's a video showing the net effect, listen to the sound. The button is wired to PTT IN and the PTT OUT is done via OC Pin 7. More info will come.

**Comment by sjk7** [comment]
Ok, I'd like to know if/how to replicate the hardware switch on an HL2, then I feel sure I will see it.

Steve

**Comment by w-u-2-o** [comment]
On the 3.5mm stereo (tip/ring/sleeve) front panel connector wire a switch
between the ring and sleeve contacts.

In VAC make sure "Allow PTT to override..." is turned off.

You can also PTT via serial port for Thetis for true remote operation.
Provision a serial port that supports CTS/RTS signaling (most USB adapters
work fine). Wire a switch across pins 7 and 8. Go to Setup >
Serial/Network/Midi CAT and enable the PTT control port with RTS checked.

73,

Scott

**Comment by sjk7** [comment]
ok, thanks Scott, but I need to know which of these schemes the OP is using
so I can replicate 100%.

I think I stumbled across the thread that polls the PTT today. Its just a
normal priority thread with async and await for 1 millisec.
I have changed it to the more usual synchronous code and Thread.Sleep(1).
It shouldn't behave any differently, but maybe it does, so we need to check
when I issue the next revision msi file. I am unsure even why the
threadProc was marked async. I don't get it.

**Comment by sjk7** [comment]
Also investigating dmp file.

**Comment by RdWing** [comment]
I am using RCA PTT in, and Open Collector pin 7 out to key the amp, if that helps. I will keep eyes peeled for the next build, and will also try moving the amp over to PTT out which should parallel our PTTOUT that you have on the HL2.

**Comment by sjk7** [comment]
Ah so, as I see it, I am looking in two places. One for detection of key
down, the other for toggling pin 7? Or do you know better?

Thanks for your continued interest in getting things right!
Steve

**Comment by RdWing** [comment]
QST QST, egg on my face. I screwed up.
I think my Wavenode swr/power meter software was somehow interfering with keying Thetis. It's a windows program that connects to my USB station monitor.
I closed the program and keying seemed to work properly in Thetis. It's a little strange because all the keying is done physically on the radio, but I suppose Thetis is involved.

Sounds like there's some incompatibility between the meter program and thetis, perhaps tying up some resource or something. So, apologies for raising this report and thank you for your contributions, they are greatly appreciated. I will raise an issue with the Wavenode developers and see what happens.

**Comment by sjk7** [comment]
No egg anywhere, for I appreciate the help in resolving this and other issues. 

Steve

**Comment by RdWing** [comment]
So, I spoke to the developer of the Wavenode software and the initial report is that nothing has changed. I will need to investigate how far back the problem goes.
[Here's a video](https://devsecopsit-my.sharepoint.com/:v:/p/jon/EXNlSObc5hlIokct_aJY61kBiRIXLBTPc1bvxlsSpNB-xA?e=KaclDu) that shows it as well. Really interesting when the meter software is closed the issue disappears.

**Comment by sjk7** [comment]
Hello!

Good vid!

I spose what I need to know is how that Wavenode 'communicates' to Thetis.
Any clues? Any developer docs?

Thanks

Steve

**Comment by RdWing** [comment]
That is the very strange thing...the Wavenode doesn't communicate or interact with Thetis at all.
Wavenode says they use Windows Messaging, fwiw.
[WN_InOut.zip](https://github.com/sjk7/Thetis-2.9.0/files/11400893/WN_InOut.zip)

**Comment by w-u-2-o** [comment]
Why would a WaveNode sensor need to communicate with Thetis?

**Comment by RdWing** [comment]
It doesn't, and has no faculty to do so. However the only commonality is that both programs run on the computer.
But definitely something between the two is causing this strange behavior.

**Comment by RdWing** [comment]
@sjk7 I ran Process Monitor to dive in.
It appears that when the PTT is asserted on the radio, Thetis.exe spawns and immediately kills a thread.

During *normal operation* here's what that looks like (I've hidden the UDP events for clarity). Every thread create and exit occurs upon key down.

**Thetis Thread Create**
![image](https://user-images.githubusercontent.com/19214916/236411498-180e89f1-5fdb-4333-933f-92a12fc3636e.png)
![image](https://user-images.githubusercontent.com/19214916/236411366-8cd1aa35-2027-4833-976a-7fa0d27b2a1d.png)


**Thetis Thread Exit**
![image](https://user-images.githubusercontent.com/19214916/236411407-c2480a70-9708-4883-8bc6-6c718ee70456.png)


In the Wavenode meter app in Process Explorer (wn2.exe), I see the following in the stack for the process. Perhaps there is something conflicting.

> ntoskrnl.exe!KeSynchronizeExecution+0x7db6
ntoskrnl.exe!KeReleaseInStackQueuedSpinLockFromDpcLevel+0xba5
ntoskrnl.exe!KeReleaseInStackQueuedSpinLockFromDpcLevel+0x1fc7
ntoskrnl.exe!KeWaitForMutexObject+0x256
ntoskrnl.exe!ObReferenceObjectByHandle+0x9a9
ntoskrnl.exe!NtReadFile+0xaf7
ntoskrnl.exe!NtReadFile+0xd3
ntoskrnl.exe!_setjmpex+0x8ce8
wow64cpu.dll!TurboDispatchJumpAddressEnd+0x544
wow64cpu.dll!TurboDispatchJumpAddressEnd+0x224
wow64cpu.dll!TurboDispatchJumpAddressEnd+0x5c6
wow64.dll!Wow64KiUserCallbackDispatcher+0x67d
wow64.dll!Wow64LdrpInitialize+0x12d
ntdll.dll!EtwLogTraceEvent+0x2613a
ntdll.dll!EtwLogTraceEvent+0x19f30
ntdll.dll!LdrInitializeThunk+0xe3
ntdll.dll!LdrInitializeThunk+0xe

Not sure if this helps at all. Is there a better way I can collect data to investigate this?

**Comment by sjk7** [comment]
Hello,

If you disable PS, you will probably find no more spawned threads. PS
spawns 2 threads as it engages. This is normal operation.

Steve

**Comment by RdWing** [comment]
Thanks. I think the threads thing is a non sequitur. However, the issue persists and is real, and I can't find a better way to debug it. Any suggestions are greatly appreciated.

I have discovered that its not just keying coming in from PTT lines, but also via TUN and MOX, and just thetis gui in general becoming less responsive when wn2.exe is running.
[Requisite video](https://devsecopsit-my.sharepoint.com/:v:/p/jon/EZmV2T74MpxEr85Ii1zuQEsBi_38lzEGa3eVLcyu-I_1qw?e=D1iNeg)

**Comment by sjk7** [comment]
The only thing I can think of that might help is to pose the question

Are there any earlier versions of Thetis where this issue does *not* exist?

Steve

**Comment by RdWing** [comment]
This issue goes back to at least 2.9.0.8. Am testing older versions currently. Something else I noticed is that even the clack of the relays appears to become delayed, instead of the two or more relays switching simultaneously in unison, when the wavenode software is open one can hear a one-two-three of relays in the radio. Strange.

**Comment by RdWing** [comment]
2.9.0.6 does it too.

**Comment by RdWing** [comment]
2.9.0.6 does it too, somewhat. There is still a hiccup on 2.9.0.6 but not the multi-seconds of delay. Tested with a fresh database.
If in CWL or CWU, slow keying doesn't occur. But as soon as I switch to any other mode, boom, it's back.

**Comment by sjk7** [comment]
Interesting. I have nothing to add at the moment, will give it some thought
and let you know if I do.

I will probably end up replicating your setup here, but with the HL2 once
most of the coding is complete, especially regarding the PS bug, etc

Steve

**Comment by RdWing** [comment]
Thanks. In the meantime I'm going to capture and inspect the network traffic between Thetis and the radio and see if there's something I can point to there, maybe a difference in timing or something. Finally, I'll wade into slightly uncharter waters: I hope to instrument both Thetis and WN2.exe and see if I can't find something there too.

Thanks for your help.
