### ISSUE TITLE
2.9.0.11 does not start on Apache 7000DLE if Firmware RX(1/2) Sample Rate is set to 153600[BUG]

### ISSUE THREAD

**Issue by jeffreydoran** [sjk7/Thetis-2.9.0#2]
**Describe the bug**

Firmware 2.1.23
Protocol 2 (v3.9)

2.9.0.11 does not start on Apache 7000DLE if Firmware RX(1/2) Sample Rate is set to 153600

**Desktop (please complete the following information):**
-OS WIndows 11

Jeff NJ2US

**Comment by sjk7** [comment]
This could be awkward, since I don't have a 7000, but thanks for reporting. Some Qs:

Do you see any errors pop up when you start the radio?

Does this work correctly on Richie's version 2.9 of Thetis?

Does it start correctly on all other sample rates (including higher ones)?

See if you can find ErrorLog.txt in C:\Users<yourusername>\appdata\roaming\openhpsdr\Thetis\ ...

Note that you can get the exact path into the windows clipboard from the setup/where you choose your radio tab -- see the new text on the bottom left of the tab.


Cheers!
Steve

**Comment by NC3Z** [comment]
I will pipe in with a few comments as I also just ran into this issue on my 7000DLE and trying to run .11

No error when trying to start, but simply the power button will not start Thetis.

If I start Thetis in a lower sample rate all is fine, but if I go into setting and switch to 1.536 then Thetis just simply closes, no errors.

This only happens on the 1.536 sample rate, which is the top rate.

No issues with Richie's

Sorry, I reverted and dont have the error log, will try later to capture it.

Gary NC3Z

**Comment by jeffreydoran** [comment]
ErrorLog.txt found, Starting Thetis with sample rate higher than 768k did not append the log with any new data. 

Jeff NJ2US

**Comment by sjk7** [comment]
Did anyone notice that I left a '0' off the end of that particular sample rate?
You probably knew this already, but you will need a 10Mbps ethernet connection for that ridiculously high sample rate.

LOL :-)

**Comment by sjk7** [comment]
I'll upload a fix once I get back on my own PC later. Thanks for the report.

**Comment by sjk7** [comment]
Installers are now updated, with any luck.

**Comment by sjk7** [comment]
I'm having issues with git closing these issues as soon as I reference them.

**Comment by sjk7** [comment]
So, I did indeed typo in the code by leaving off a zero for this particular sample rate. However, something funky is going on with the way that, if the connection protocol differs from the chosen protocol, the damn thing is not doing the right thing. I need to test this more on a friend's machine -- he as an ANAN-100, so i can see the bug on his machine only and work with it from there.

**Comment by sjk7** [comment]
Please ignore those labels. I have no idea where they came from. Can you report back whether it is working, or not in the latest release? (Assuming the 32-bit version is running on your machine, because the installer has gone a bit mad)

**Comment by DH1KLM** [comment]
Just compiled 2.9.0.15 x64 and there it is working with highest samplerate and even if RX2 and VAC2 is enabled.
So no problem here.

**Comment by sjk7** [comment]
Great, will close. Thanks for the useful feedback :-)
