### ISSUE TITLE
[BUG] Thetis window's position on the screen is no longer remembered

### ISSUE THREAD

**Issue by NC3Z** [sjk7/Thetis-2.9.0#20]
**Describe the bug**
In .8 and before if you moved the position of the UI or resized it then that would be saved and recalled when you started up Thetis again. Now I can not get a resize or a move to be saved.

**To Reproduce**
1. Move or Resize Thetis
2. Close and then restart

**Expected behaviour**
Position should have been saved.

 - OS: Win 11

**Comment by sjk7** [comment]
Quite right, it should remember the window position and size.

**Comment by sjk7** [comment]
Once I upload revision 19 or more, you should not see this any more. I tested it both in expanded and collapsed mode. It's not uploaded yet, maybe tonight or tomorrow.

Steve

**Comment by sjk7** [comment]
Hi! I just uploaded the executable containing the fix:
https://github.com/sjk7/Thetis-2.9.0/releases/download/v2.9.0.4/Thetis-v2.9.0.x64.msi

**Comment by oldjackbob** [comment]
Steve, please know that this humble Thetis user is hugely grateful for your tireless support!

Mark

**Comment by NC3Z** [comment]
@sjk7 Yes .19 fixes the position and size, thanks.
