### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kingsqueak** [sjk7/Thetis-2.9.0#23]
Windows 11 Pro x64 current patch level
2.9.0.19 Thetis downloaded today

GUI comes up, click start, it crashes/closes completely.

Tried starting, going into Setup and going from Proto 2 to Auto.
Radio started, as soon as I zoomed the pan adapter, the app crashed and closed.

2.9.0.15 was stable for me.

**Comment by sjk7** [comment]
Try a database reset. ALso, look in ErrorLog.txt in the data folder. You can get to it from the first setup tab, bottom left. Also try disabling VAC and see if he starts then. Its probably a bad audio setting.

**Comment by kingsqueak** [comment]
A db reset fixed it. 2.9.0.19 is now up and running.

The VAC seems to be behaving vastly better.
