### ISSUE TITLE
[FEATURE] QSO Timer AutoStart

### ISSUE THREAD

**Issue by NC3Z** [sjk7/Thetis-2.9.0#25]
Would like to see the expansion of the QSO Timer (General > Options > Options 2) so that there is an option to have the Timer autostart when Thetis starts. Right now you must manually start it.

Further it would be nice that the timer synchronize to the next 10 minute interval to start so that the reminder pops up on the 10's (e.g. :10, :20, :30, etc.)

**Comment by sjk7** [comment]
Ok, will take a look to see what else breaks when I do that (!)

Steve

**Comment by NC3Z** [comment]
Dont worry, we actually enjoy trying to find things broken, it is all part of this adventure.😁

**Comment by sjk7** [comment]
I had a brief look. It looks to me like it causes a timer/clock icon to appear on the statusbar when it is active. Perhaps you could tell me more about it/point me to it in the manual as I obviously need to learn more about it.

Steve

**Comment by w-u-2-o** [comment]
The QSO timer is a feature that was added by Richie. It's a very useful, well liked feature. It's a timer that appears on the bottom status bar:

![Capture4](https://user-images.githubusercontent.com/100238155/235304715-5525712a-a710-4df3-a86b-6d538aa0f123.JPG)

Left click on the timer starts and stops it. Right click resets it to zero.

Options for the timer appear here:

![Capture5](https://user-images.githubusercontent.com/100238155/235304799-d0d3e420-4543-4d45-8e0b-9b209974c338.JPG)

Gary would like an additional option entitled "Start with Thetis". The use case for that is obvious: never forget to turn it on again!

And also an option that might be titled "Sync to the "tens"" or something like that. This option would have to override the normal user specified time fields. The use case for this might be more of an American rag-chew thing, as it has become somewhat traditional in large, multi-station rag-chews for all participants to ID on the identical ten minute boundaries (10 after the hour, 20 after the hour, etc.) such that the flow of conversation is not continually interrupted by callsigns.

73!

Scott

**Comment by sjk7** [comment]
Hello,
Please see why I am not currently servicing any feature requests, unless of course you'd like to employ me to do so! :-)

https://github.com/sjk7/Thetis-2.9.0/releases/tag/v2.9.0.4
