### ISSUE TITLE
Crash when started with Power button when VAC ringbuffer values are below some threshold [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [sjk7/Thetis-2.9.0#27]
**Describe the bug**

Thetis will launch, then crash when started with the Power button when VAC1 ringbuffer values are below some threshold which seems to vary with VAC1 main buffer size.

Tested only with ASIO and 48KHz sample rate.

Portaudio buffer size does not seem to matter, it may be set to 0.

This only happens at startup. Assuming a good startup, VAC1 parameters can then be set to any combination without the app crashing. Ringbuffers can be set to 0 at that point. The crash only occurs at the first instantiation of VAC after startup.

**To Reproduce**

Set VAC1 to ASIO, a pair of valid ASIO devices, 48KHz and enabled. Set portaudio buffers to 0. Save to a transmit profile. Test to make sure VAC1 works. Select that transmit profile as the last active transmit profile so that it is enabled at startup.

Quit and relaunch the app.

Prior to using the Power button, open Setup > Audio > VAC1 and set VAC buffer and ringbuffer to explore the following conditions:

With buffer 512 a ringbuffer setting below 6 and 6 will cause a crash when the power button is activated. Above that is OK.

With buffer 64 a ringbuffer setting below 1 and 1 will cause a crash when the power button is activated. Above that is OK.

Again this behavior is only seen at initial startup of the app. Once it has successfully started VAC parameters may be changed without restriction.

**Expected behaviour**

No possible combination of VAC settings should allow a crash at startup or any other time after startup. Audio may not run, or may sound terrible, but the app should not crash.

**Desktop (please complete the following information):**

ANAN-8000DLE Protocol 2 FW 2.1.18, Voicemeeter Potato as ASIO device, Thetis 2.9.0.19, Windows 10 Pro

**Additional context**

Other than the above issue, the changes to VAC are ***FABULOUS***. I have a very advanced setup with a Presonus Studio 192 Mobile interface locked to a GPSDO wordclock, ANAN locked to GPSDO 10MHz (so all are on the same clock domain), Voicemeeter Potato as the software "patch panel", and Reaper DAW being used as a mixer. I have never been able to use a VAC buffer size of less than 512. I am now using a VAC buffer of 64, a portaudio buffer of 0, and ringbuffer of 2. If I bump VAC buffer to 128 I can go to all zeroes (albeit only after startup per the above bug). In either case very LOW latency and stable. Well done, thank you!

**Comment by sjk7** [comment]
We had a similar one the other day. I think it centres on the (broken) ability to set the buffers to zero. Some drivers freak out in this case, although not all do. It will probably be cured by translating any zero buffer request sizes as "1". I will try it, assuming I can get it to fail here. Both the new asio and new portaudio seem to interpret the "0" incorrectly. 

It should mean "make the buffers as small as you reasonably can" but somehow the new versions take it as literally a 0-byte buffer.

Steve

**Comment by w-u-2-o** [comment]
This isn't acting like 0 = crash. It's "less than some number that is VAC buffer size sensitive = crash". 

And, it's only on startup. I can set any VAC config. I want after startup (unless those changes are being ignored somehow?)

**Comment by sjk7** [comment]
Could be the settings are ignored indeed. I am chasing one where I cannot the correct tx profile to come back after a band change. Only manually reloading the profile fixes it. I suspect it is related.

I will close this for now, as my audio buffer is slightly more subtle, and it may well fix the issue -- it will be in the next revision i package as an msi today or tomorrow. Basically if *ever* ASIO via portaudio gets a strange buffer request, he will just go the minimum latency as set in the hardware, so its not just a 'zero' thing. Just refer me back to this ticket should it not solve the problem

Steve

**Comment by sjk7** [comment]
Revision 20 has been uploaded

**Comment by w-u-2-o** [comment]
The crashing problem has been fixed in this release.

However, there are other problems now with the ability to adjust ringbuffer
size and also VAC instability with the AmpView window active. More to
follow when I get a coherent set of observations together and a procedure
to reproduce them.

**Comment by w-u-2-o** [comment]
No longer crashing at any combination of settings, not at startup or any
other time.

No TX audio via VAC (#35).

**Comment by sjk7** [comment]
#1 priority is to get rid of crashing bugs. We can always work from there. Uninstall thetis first, and this one will work. This is what happens when I do not bump the revision correctly -- you see now why I do it? If I dont (and this includes dll versions) the installer is not smart enough to overwrite the files. Meh.
