### ISSUE TITLE
Console appears, disappears, then fades in on app launch [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [sjk7/Thetis-2.9.0#28]
**Describe the bug**

Console appears, disappears, then fades in on app launch. This happens very quickly.

**To Reproduce**

Launch the app.

**Expected behaviour**

On launch the console should just fade in.

**Screenshots**

Can make a video recording on request.

**Desktop (please complete the following information):**

ANAN-8000DLE Protocol 2 FW 2.1.18, Voicemeeter Potato as ASIO device, Thetis 2.9.0.19, Windows 10 Pro

[NVIDIA System Information 04-24-2023 07-59-19.txt](https://github.com/sjk7/Thetis-2.9.0/files/11310144/NVIDIA.System.Information.04-24-2023.07-59-19.txt)

**Additional context**

Not a big deal, just though I'd mention it since I saw it.

**Comment by sjk7** [comment]
Yeh! I finally fixed this over the weekend. It was a ROYAL pain in the arse. It will be sorted on the next release. Note that if you run it under Visual Studio, you won't see a difference but in the Real world its fine now.
