### ISSUE TITLE
Add "Always On Top" button to AmpView display and allow AmpView display to exist without Linearity control window [FEATURE]

### ISSUE THREAD

**Issue by w-u-2-o** [sjk7/Thetis-2.9.0#30]
**Is your feature request related to a problem? Please describe.**

It is convenient to place the AmpView display over an unused area of the spectral display. This is particularly true on screen space-constrained systems like laptops or Andromeda. Unfortunately, once placed in that manner any use of the main console causes the console to come to the foreground, obscuring the AmpView display. This most typically happens when adjusting RF drive while watching the AmpView display to gauge its effects on amp linearity and saturation.

Also, once the AmpView display has been enabled via the linearity control window, it is rarely necessary to keep the linearity control window open as it is taking up valuable screen real estate.

**Describe the solution you'd like**

Add an "Always On Top" option checkbox on the AmpView window similar to that found on the linearity control window.

Make the AmpView display modeless relative to the state of the linearity control window.

**Describe alternatives you've considered**

None.

**Comment by sjk7** [comment]
Hello,
It's probably not needed. 9/10 when we see something like this, it is because the window is not owned properly, and I suspect this is the case here. If it were owned by Console, it would have lower z-order and thus would show on top.

I am not a native c# speaker, buit afaik 'always on top' is almost always the wron solution. Certainly in the win32 api always on top makes it on top of ALL windows, so if u minimze the main console. it will still be there, and this is non-standard and annoying UI behaviour.

If instead console were to own the window, it would stay on top of console only, and I think this is what the user wants.

**Comment by w-u-2-o** [comment]
Roger, copy all. Not sure how best to fix it. Just as long as it is on top when desired ;-)

Same for the Setup window, too.

**Comment by sjk7** [comment]
Setup form was correctly owned since ever in my version. I ported it across right from the first commit, I think.

**Comment by sjk7** [comment]
Ampview is now owned by console, so now we get the default windows behaviour for an owned window. Let me know if I misunderstood when I get the next revision out of the door.

Steve

**Comment by w-u-2-o** [comment]
Setup form will currently remain on top of the main window in 2.9.0.19  (it did not do this in 2.9.0.8) so this bodes well for AmpView, thanks!

**Comment by sjk7** [comment]
> Setup form will currently remain on top of the main window in 2.9.0.19 (it did not do this in 2.9.0.8) so this bodes well for AmpView, thanks!

Yes, this drove me scatty!

Steve

**Comment by sjk7** [comment]
Revision 20 has been uploaded

**Comment by w-u-2-o** [comment]
This is working as expected. The new window ownership properties are
keeping the settings, linearity and ampview windows on top. The linearity
window can be dismissed without losing the ampview window. In fact the
"Always on top" option could be removed from the linearity window.

However...this begs the question: what about users who prefer for these
windows to not be on top? Now they don't have the option.

And...it begs the same question for all the other windows that either
already have an "Always on top" option (e.g. Diversity) or don't have any
option at all and are not "owned" (e.g. wave, equalizer, XVTRs, memory...)

I'd argue that having the "Always on top" option for ALL of these windows
is a better approach for the user (maybe not the programmer!) than
modifying window ownership in a way that always forces them to the
foreground.

Thanks,

Scott
