### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aicene** [sjk7/Thetis-2.9.0#33]
Thetis 2.9.0.19 x64
W10

The SWR protection actually works better, but the recovery effect still only works when the power is reapplied. For example, I turn off the tuner, the protection works clearly, turn on the tuner, SWR 1.0, the power instead of 100 watts shows 15-20 watts, and only when it is turned on again, the full power is restored. This feature worked well in old versions of PowerSDR MRX 3.4.9.

**Comment by sjk7** [comment]
OK, I will look for it. It may have been fixed when I recently had a go at repairing somewhat racy access to the variables that control this. However, I could have made it far, far worse, so we will see ...

Steve

**Comment by sjk7** [comment]
I have uploaded a new installer. Can you try it on revision 20, please?

Steve

**Comment by sjk7** [comment]
Hello,
No need for any more work on your part. I have located the problem, and fixed it.

The fix will be available in revison 23+

Steve
