### ISSUE TITLE
Enhance RX and TX ANT selection on the task bar

### ISSUE THREAD

**Issue by nj2us** [sjk7/Thetis-2.9.0#34]
Presently, the shortcut to (setting form) to select Transmit and Receive Antenna ports is a very awkward and small pull down menu.

![rx_tx_selection](https://user-images.githubusercontent.com/131202446/234587488-3d03ae2c-dac1-4f36-918a-3a39414e417b.png)

The enhancement request is to present the antenna selection by way of discreet Radio Buttons for each Antenna Port, that highlight when a particular Ant Port is selected. [RX 1] [RX2] [RX3]   /   [TX 1] [TX 2] [TX 3]  (For each TX and RX group, only one port can be selected at a time)

NJ2US

**Comment by sjk7** [comment]
Ok, but where would they go? Or perhaps I can reframe this as: Where would they _fit_?

Thanks for f/b

Steve

**Comment by nj2us** [comment]
I suggest new discreet RX Ant Select radio buttons could replace the existing mini pull down menus, exactly where they are now. Another location could be inside the information bar at the bottom of the panadapter. 

-NJ2US

**Comment by sjk7** [comment]
Hello,
Please see why I am not currently servicing any feature requests, unless of course you'd like to employ me to do so! :-)

https://github.com/sjk7/Thetis-2.9.0/releases/tag/v2.9.0.4
