### ISSUE TITLE
2.9.0.20 breaks VAC 1 TX audio in via ASIO driver[BUG]

### ISSUE THREAD

**Issue by nj2us** [sjk7/Thetis-2.9.0#35]
**Describe the bug**
No TX audio using the UMC ASIO Driver

Reverting back to 2.9.0.19 restores VAC 1 UMCASIO Driver TX audio

**Comment by w-u-2-o** [comment]
Not seeing this problem with the Voicemeeter ASIO driver.

I am seeing other problems associated with adjusting ringbuffer sizes,
however. More to follow on that when I have something coherent to report,
which I will do back in issue #27

**Comment by RdWing** [comment]
TX audio is broken in 2.9.0.20 via all VAC methods here, with all various buffer sizes and configurations. Tested via MME/DirectSound/WASAPI.
![image](https://user-images.githubusercontent.com/19214916/234958161-38bffcb5-8e53-4d15-a56a-8cb005ba9012.png)

**Comment by sjk7** [comment]
Confirmed. No VAC TX in any API!

Steve

**Comment by sjk7** [comment]
Well who wants to hear my voice, anyway? :-)
Revision 21 should be up. I was being dumb, I just left some debug code in place.

Steve

**Comment by w-u-2-o** [comment]
Steve--out of pocket tomorrow, will engage on this Saturday. Just wanted to
let you know I was thinking of you ;-)

**Comment by w-u-2-o** [comment]
Tested Rev 21: still no transmit audio via VAC using ASIO or MME. Did not
pursue testing other drivers.

8000DLE, FW 2.1.18, Windows 10 Pro

**Comment by RdWing** [comment]
It is now working for me on R21.

**Comment by sjk7** [comment]
Yes, you may need to uninstall the app before installing this one. I don't think I bumped the version on channelmaster.dll, so it wont necessarily overwrite the existing one (and it's broken).

I think i uploaded another one minutes after, thinking I had then deffo bumped CHannelmaster, so you might need to download it again.

**Comment by w-u-2-o** [comment]
Naughty, naughty!

Today's adventures are about to begin. Won't get to this
(uninstall/reinstall) until after your bedtime this evening (if you
actually sleep?)

Thanks,

Scott
