### ISSUE TITLE
AmpView display affecting VAC performance [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [sjk7/Thetis-2.9.0#36]
**Describe the bug**

Using ASIO, can run buffer 64, ringbuffer 2/2, portaudio 0/0, which is damn good. However, if I bring up the AmpView display the resampler under and overrun counters will go crazy during transmit (using two tone since VAC is still broken for TX). I have to increase ringbuffer to 7/7 to solve that problem and make VAC stable with AmpView display.

Increasing main VAC buffer to 128 does not mitigate the situation. It arguably makes it worse, because at 128 I can make ringbuffer 0/0 without AmpView display, but with AmpView active the ringbuffer again needs to be 7/7 for stable operation during transmit.

**To Reproduce**

Can't provide precise directions since everyone's VAC setup is necessarily a little different. However, in general

- Set up VAC for minimum latency (right on the edge of resampler stability)
- Enable AmpView display and make a transmission with PureSignal active.
- Note whether an increase in VAC ringbuffer setting is necessary to regain resampler stability.

**Expected behaviour**

AmpView display should not affect VAC performance.

**Desktop (please complete the following information):**

8000DLE, FW 2.1.18, Thetis 2.9.0.21, Windows 10 Pro

**Comment by nj2us** [comment]
My observation is that rolling Port Audio up to 1 for both in and out (Manual of course) settles the OF/UF, using ASIO UMC drivers, buffer 64, Ring Buffer 10/10. I've usually run Port Audio 0/0, and had some belief that PortAudio was not used with ASIO drivers. Port Audio 0/0 instantly gives me runaway OF/UF. All testing done with AMP VIEW enabled, which remains "on top"
NJ2US

**Comment by sjk7** [comment]
yeh, its probably not a bug, but simply an artifact. You have to be very careful what you run on the PC, and even minimising a window will cause a glitch when there is hardly anything in the buffers. I will check the ampview is running on a low-priority thread, but I think it is already. I can lower its priority more, but yeh, this could be well, just physics. And Windows, lol

**Comment by sjk7** [comment]
BTW I uploaded a new revision to deal with no audio in TX. Has it not fixed it for you, @w-u-2-o ?
You may have to uninstall the app before putting this one in, because I am not sure I bumped the version of ChannelMaster.dll, so it may not overwrite the one that exists.

**Comment by sjk7** [comment]
> My observation is that rolling Port Audio up to 1 for both in and out (Manual of course) settles the OF/UF, using ASIO UMC drivers, buffer 64, Ring Buffer 10/10. I've usually run Port Audio 0/0, and had some belief that PortAudio was not used with ASIO drivers. Port Audio 0/0 instantly gives me runaway OF/UF. All testing done with AMP VIEW enabled, which remains "on top" NJ2US

I wish what you said was true, and that those buffers would not be a factor with ASIO. But those buffers are always active. As per Warren's talk (online) they are there for long-term corrections and rate-matching.

**Comment by sjk7** [comment]
> **Describe the bug**
> 
> Using ASIO, can run buffer 64, ringbuffer 2/2, portaudio 0/0, which is damn good. However, if I bring up the AmpView display the resampler under and overrun counters will go crazy during transmit (using two tone since VAC is still broken for TX). I have to increase ringbuffer to 7/7 to solve that problem and make VAC stable with AmpView display.
> 
> Increasing main VAC buffer to 128 does not mitigate the situation. It arguably makes it worse, because at 128 I can make ringbuffer 0/0 without AmpView display, but with AmpView active the ringbuffer again needs to be 7/7 for stable operation during transmit.
> 
> **To Reproduce**
> 
> Can't provide precise directions since everyone's VAC setup is necessarily a little different. However, in general
> 
> * Set up VAC for minimum latency (right on the edge of resampler stability)
> * Enable AmpView display and make a transmission with PureSignal active.
> * Note whether an increase in VAC ringbuffer setting is necessary to regain resampler stability.
> 
> **Expected behaviour**
> 
> AmpView display should not affect VAC performance.
> 
> **Desktop (please complete the following information):**
> 
> 8000DLE, FW 2.1.18, Thetis 2.9.0.21, Windows 10 Pro

even with 7/7, this is pretty respectable latency considering how many threads there are in this app. There is much more latency from equalisers, CFC , and so on, so you can afford to make them even higher if you are using them.

**Comment by sjk7** [comment]
I have lowered the thread priority of the Ampview. It should not interfere with the audio, unless the buffers are non-existent or tiny. This is a case of "it's the best I can do"

Steve

**Comment by w-u-2-o** [comment]
Thanks, Steve. Will try on the next release.

Note: it can't be that I'm not "careful" what I run, because I can run two
browsers, live video and stream on OBS and it makes no difference as long
as I don't have AmpView open. It's an internal issue in Thetis.

Also, 7/7 is not that respectable.

Rolling portaudio up to 1/1 or even 100/100 makes no difference for me.
Must be a difference between Voicemeeter drivers and Behringer drivers.

Thanks,

Scott

**Comment by torrenthd** [comment]
I was facing this issue in previous Richie's release, so it is not a bug introduced by Steve.

**Comment by w-u-2-o** [comment]
Yes, plenty of bugs and problems predate Steve. Plenty of bugs that predate
Richie, too, and he squashed a lot but not all of them. That's why people
get very excited when people like Steve and Richie develop an interest in
the software and start squashing them! :-)

BREAK

The thread priority change did not make a difference here. Ringbuffer needs
to be at least above 5, 7 for some margin, to allow AmpView to run
without causing audible artifacts and under/overruns on VAC.

Thanks,

Scott
