### ISSUE TITLE
[BUG]PS-M not available when toggling PS-A button after enabling in AmpView advanced menu

### ISSUE THREAD

**Issue by W1AEX** [sjk7/Thetis-2.9.0#37]
**Describe the bug**
After playing with 2.9.0.21 could not get PS-M to work after enabling in the the AmpView Advanced menu. Just saw your note that it would be back in a subsequent release. Love this feature Steve so glad it will come back!

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'AmpView'
2. Click on 'Enable PS-M'
3. Toggle PS-A
4. PS-M not available

**Expected behaviour**
When enabled in AmpView advanced menu PS-A should toggle to PS-M

 - OS: Windows 11

**Additional context**
73,  Rob W1AEX

**Comment by sjk7** [comment]
OK, appreciate the comment. Will mark as 'not a bug' though since it needs some more work.
Thanks!
