### ISSUE TITLE
Rx BYPASS on Tx

### ISSUE THREAD

**Issue by eu2av** [sjk7/Thetis-2.9.0#39]
Hello Steve! Version 2.9.0.20 did not have this problem. I use a power amplifier, for P-SA I take the signal from RX-BYPASS . After the transmission, when switching to reception, the reception disappears. Unchecked "Rx BYPASS on TX" in the "Ant/Filters" tab of the Setup, and everything starts working fine. If you set the checkbox to "Rx BYPASS on Tx" or to "Ext 1 on Tx", then this effect occurs, RX does not work.

**Comment by RdWing** [comment]
Which ANAN do you have? I am using Rx Bypass here for an external sampler on R21 without issue.

**Comment by eu2av** [comment]
I have firmware 2.1.18. With Thetis version before 2.9.0.20 everything works correctly

**Comment by oldjackbob** [comment]
After reading #39 I've determined that bug #38 is related to the same problem, as I also usually operate with "RX BYPASS on TX" enabled. However, if I disable "RX BYPASS on TX" then RX1 behaves as expected and the problem described in #38 does not occur.

Mark

**Comment by sjk7** [comment]
Lemme lock this. It's the same as #38 
Steve

**Comment by sjk7** [comment]
I am going to upload a series of installers until we find out where the problem comes to light. It's awkward, as I cannot replicate it here on HL2 hardware, so far. Please download again, and see if the problem still persists. We can go from there. I switched the conversation to #38 
Steve

**Comment by sjk7** [comment]
Can someone experiencing this issue try the following download and feed back?
https://github.com/sjk7/Thetis-2.9.0/releases/download/v2.9.0.4/Thetis-v2.9.0.x-TRYME-64.msi
