### ISSUE TITLE
[BUG] No audio through VAC2

### ISSUE THREAD

**Issue by DH1KLM** [sjk7/Thetis-2.9.0#4]
No audio through VAC2.
VAC2 graph shows a straight line. There is no movement.

Power button does nothing when VAC2 is active. MOX flashes once briefly.
It doesn't matter whether RX2 is active or not.

Tried MME, Windows Direct Sound, WASAPI and WDM-KS. None of these drivers work with VAC2. (in VAC1 all are working)
All sample rates have been tried.

WIN10, ANAN7000, protocol 2.

**Comment by sjk7** [comment]
Thanks. I have never even used VAC2, let alone coded anything for it. VAC1 is OK?

**Comment by DH1KLM** [comment]
Yes VAC1 is working without problems.

**Comment by sjk7** [comment]
Yes, unfortunately portaudio is written in c++, which has zero support for Unicode. So this one I cannot fix. Are the soundcards mit umlauts working and being selected OK, though?

**Comment by sjk7** [comment]
Hello, I now have VAC2 working. But there is only audio when RX2 is on. Is this the correct behaviour ?

**Comment by NC3Z** [comment]
Yes only when RX2 is running will VAC2 work.

**Comment by sjk7** [comment]
@NC3Z OK, working well here. Will build release soon. Source is up2date on GH if you want to build yourself.

**Comment by sjk7** [comment]
Thanks both [DH1KLM](https://github.com/DH1KLM) and [NC3Z](https://github.com/NC3Z) for reporting and answering my question. 

I am closing this because I believe it is working properly (only works when RX2 is on). It's not as fully featured as VAC1. See my notes in the Changelog. Any issues, I have no problem reopening this ticket!

Steve

**Comment by DH1KLM** [comment]
Thanks for fixing this.
Just compiled your latest code. VAC2 seems to work without problems so far.
