### ISSUE TITLE
CW Memories from Keyboard[FEATURE]

### ISSUE THREAD

**Issue by va7qi** [sjk7/Thetis-2.9.0#40]
**Is your feature request related to a problem? Please describe.**
CW Memories (from CWX on the top line) are operated by the mouse.  When the contents of a memory is sent, the keyboard is turned off and you have to click on the Keyboard button to re-enable the keyboard.

**Describe the solution you'd like**
suggested improvements:

1. keep the keyboard on when using the memories
2. make keyboard keys F1 - F9 send the memories

This will allow the operator to send all CW from the keyboard without having to use the mouse.

**Describe alternatives you've considered**

**Additional context**

73 de va7qi,        ....Erik.

**Comment by sjk7** [comment]
Thanks for the feedback. Will look in due course.

Steve

**Comment by sjk7** [comment]
Hello,
Please see why I am not currently servicing any feature requests, unless of course you'd like to employ me to do so! :-)

https://github.com/sjk7/Thetis-2.9.0/releases/tag/v2.9.0.4
