### ISSUE TITLE
Meter needle missing during TX on EDGE style meter [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [sjk7/Thetis-2.9.0#41]
**Describe the bug**

2.9.0.26 "try me" version.

With the _Edge_ style meter type selected in Settings > Appearance > Meter

During TX no meter needle is seen on the meter. I have not tried all meter types, but this is true for Mic and ALC Group.

The numeric readout does appear and is functioning.

This problem does not occur if meter type is set to _Original._

**To Reproduce**

Select the _Edge_ style meter type selected in Settings > Appearance > Meter.

Make a transmission.

**Expected behaviour**

Meter needle should appear.

**Desktop (please complete the following information):**

ANAN-8000DLE, FW 2.1.18, Windows 10 Pro.

**Additional context**

This is kind of a crazy one. Can't see what else might have changed recently to cause this. More "brittleness?"

Thanks,

Scott

**Comment by oldjackbob** [comment]
I'm seeing the same behavior that Scott is reporting, none of the Mode Selections for the Edge style meter are working except Fwd SDR....in that mode both needles (Fwd Pwr and SDR) are working during transmit (running TRY ME 2.9.0.26).

Mark

**Comment by sjk7** [comment]
This is a good catch. My eyes hurt.

Steve

**Comment by sjk7** [comment]
Should be fixed in rev 27 download

**Comment by w-u-2-o** [comment]
Working well here! Super fast fix!

Thanks!

Scott
