### ISSUE TITLE
Unable to tune

### ISSUE THREAD

**Issue by va2jn** [sjk7/Thetis-2.9.0#42]
**Describe the bug**

I have a Flexradio TGXL tuner (automatic) when I tune I have a low power indication on the TGXL and unable to tune, 20w for the tune.
With version 2.9.0.8 I have no problem.
I have this problem since with each of your versions

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by nj2us** [comment]
Temporarily DISABLE/UNCHECK  "Enable Protection" and "DISABLE on TUNE Pwr <35"
I suspect your transmitter is "folding back" TX power.
Just a thought.

-NJ2US

**Comment by va2jn** [comment]
I have no problems with the official version even 2.9.0.8. The problem is software

VA2JN

**Comment by nj2us** [comment]
Did you try my suggestion?

**Comment by va2jn** [comment]
Same problem

**Comment by va2jn** [comment]
Correction all it's ok ,,,, thank's

:)

**Comment by sjk7** [comment]
Closed.

**Comment by RdWing** [comment]
I have run into this problem, on 2.9.0.8 I can run with SWR Protection on with the "disable under 35W" checked.
On these releases it cuts out the power while my tuner is tuning, and getting it to recover is tricky.
