### ISSUE TITLE
Two tone inoperative in CWL and CWU modes [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [sjk7/Thetis-2.9.0#44]
**Describe the bug**

Two tone function not operating when mode is CWL or CWU.

**To Reproduce**

Change mode to CWL or CWU. 
Assert two tone.
Observe no output.
Change to any other mode (LSB, USB, etc.)
Assert two tone.
Observe proper two tone output.

**Expected behaviour**

Two tone functions in all modes that allow transmission.

**Desktop (please complete the following information):**

2.9.0.26 "try me", ANAN-8000DLE, FW 2.1.18, Windows 10 Pro.

73,

Scott

**Comment by sjk7** [comment]
I don't _think_ two tone has ever been available for CW modes. Im my mind, it doesn't make much sense as it is not a mode that requires linearity, other than pulse-shaping.

**Comment by w-u-2-o** [comment]
OK, no problem for me! Good to go if you want to close it. Wondering if that is what the other gentleman's problem was?

**Comment by sjk7** [comment]
Guys, you need to try these things in the version I forked from. I am touching Richie's code as little as possible so it will literally intergrate with his code with a single click. No sense in overwhelming the guy!

Steve
