### ISSUE TITLE
Change AmpView display to DirectX [FEATURE]

### ISSUE THREAD

**Issue by w-u-2-o** [sjk7/Thetis-2.9.0#46]
**Is your feature request related to a problem? Please describe.**

- The AmpView display is hogging/blocking other threads, even with the Low Res option box checked and at its new, low thread priority. This is having negative effects on VAC performance (requiring larger buffers).

**Describe the solution you'd like**

- Perhaps changing the drawing method of AmpView to DirectX might help the situation.

Thanks!

Scott

**Comment by sjk7** [comment]
Yes, we need someone with DirectX skills to shift this over. Suggestions, or PRs accepted on this issue

**Comment by w-u-2-o** [comment]
Richie would be a good choice, but he seems to be on a programming hiatus.

**Comment by sjk7** [comment]
Hello,
Please see why I am not currently servicing any feature requests, unless of course you'd like to employ me to do so! :-)

https://github.com/sjk7/Thetis-2.9.0/releases/tag/v2.9.0.4
