### ISSUE TITLE
Change FFTW Wisdom method back to MEASURE [FEATURE]

### ISSUE THREAD

**Issue by w-u-2-o** [sjk7/Thetis-2.9.0#47]
Hesitating to call this a bug because perhaps the motivation is for faster installation for testing, but it would be better to make this change for normal use.

**Is your feature request related to a problem? Please describe.**

- FFTW performance is being limited because FFTW Wisdom method has been changed to ESTIMATE.

**Describe the solution you'd like**

- Change FFTW Wisdom method to MEASURE.

**Additional context**

- [Thetis-2.9.0](https://github.com/sjk7/Thetis-2.9.0)/[Project Files](https://github.com/sjk7/Thetis-2.9.0/tree/master/Project%20Files)/[Source](https://github.com/sjk7/Thetis-2.9.0/tree/master/Project%20Files/Source)/[wdsp](https://github.com/sjk7/Thetis-2.9.0/tree/master/Project%20Files/Source/wdsp)/comm.h contains the following lines:

> 
> #ifndef MY_PATIENCE
> #ifdef _DEBUG
> #define MY_PATIENCE FFTW_ESTIMATE
> 
> #else
> #define MY_PATIENCE FFTW_PATIENT
> 
> #endif
> #endif

These do not exist in any version of Thetis 2.9.0.8 or prior.

**Comment by w-u-2-o** [comment]
I forgot to attach an excellent example of the substantial performance differences between ESTIMATE and MEASURE on a reasonably modern CPU and OS architecture:

[[https://webbpsf.readthedocs.io/en/latest/fft_optimization.html](https://urldefense.proofpoint.com/v2/url?u=https-3A__webbpsf.readthedocs.io_en_latest_fft-5Foptimization.html&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=HAAPAeye6UD64Rc4etoTtQ&m=551l7hd4-m4-8CsdA5APtASKplLAXAzFFKOdxNQI7wQ&s=o7NnH2wRV71BJxq0dc2uscZXKfLnoZyGmdes44hLIDw&e=)](url)

Also, I may be misinterpreting the code, the normal mode may be PATIENT, for which we all need to be, well, PATIENT ;-)

**Comment by sjk7** [comment]
> Also, I may be misinterpreting the code, the normal mode may be PATIENT, for which we all need to be, well, PATIENT ;-)

Yes, you are!
Can't you see that FFTW_ESTIMATE is in debug builds only? At least that is the only time _DEBUG is defined on my machine!

Consider this is one of the reasons why it is a massive pain to re-install Richie's on my development machine. Waiting half an hour or more for Wisdom. So what you see there is for dev convenience only.

I any case, thanks for reminding me that I never see a use for more than FFTW_MEASURE in ham software. FFTW_PATIENT is overkill, really. Especially when lots of installations are happening. So, I won't be changing this anytime soon! 

Feel free to run fftw.exe in your thetis folder with FFTW_PATIENT if you think you can really tell the difference! LibFFTW will never overwrite a more exhaustive test with a less exhaustive one. But really, FFTW_MEASURE is all you really need to ensure it is calculated for your own machine.
