### ISSUE TITLE
I sent an invite for you to see my Thetis Changes if you would like

### ISSUE THREAD

**Issue by WD5Y** [sjk7/Thetis-2.9.0#48]
Steve,
I just have a few items that I code into Thetis. I just installed the additions after your last update with the meter needle correction today. I don't know if you would be interested in some of the items but I would appreciate your insight for sure, everything you have done and are doing with Thetis is very much appreciated. here is a list:
1) Ampview startup checkbox - this may be in already?
2) I added an audio buffer toggle to settle vac at startup - works for me but not sure if needed with your work here, not sure why but 
    seems to help synchronize the vac audio stream.
3) Added keyboard space-bar toggle for vfo-a to vfo-b TX exchange.
4) Made changes to Collapsed view to show values, etc. Also adjusted display a bit to allow more room for new metering. I have hidden the old meter because of new metering; probably would be better to be able to select hiding old meter.

If this is of no value for your work I understand, again thanks for your great work. I kept my repository private as to not interfere with other's work.

73's
Joe
WD5Y

**Comment by sjk7** [comment]
Thankyou for the invite! If there is anything I need, I will hit you up,
Steve

**Comment by WD5Y** [comment]
Thanks, I sure appreciate all you are doing with Thetis. Probably most of what I have is just thoughts, you could streamline for sure. I’m pretty old school, started back with the sdr 1000 and Janus/ozy setup, just enjoy working or mainly learning the software. 

73’s
Joe
WD5Y

**Comment by sjk7** [comment]
> Thanks, I sure appreciate all you are doing with Thetis. Probably most of what I have is just thoughts, you could streamline for sure. I’m pretty old school, started back with the sdr 1000 and Janus/ozy setup, just enjoy working or mainly learning the software. 73’s Joe WD5Y
> […](#)
> Sent from my iPad
> On Apr 29, 2023, at 7:21 PM, sjk7 ***@***.***> wrote: ﻿ Thankyou for the invite! If there is anything I need, I will hit you up, Steve — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

Keep up the good work! It's what OpenSource is all about. Find code close to what you want, then make it your own!

Cheerio

Steve

**Comment by WD5Y** [comment]
Steve,
I’m not sure what you mean by that comment, if I have done something wrong with adding a few GUI items I apologize sincerely! I really could not make someone else’s work my own for sure, as I said I am no way a developer. I would only differentiate any work that I do with Thetis to make sure someone else does not think it is either your work or Richie’s work or someone else’s because what I post is just peanuts in comparison. I usually take the true coding work that you or Richie have graciously provided and try to learn something. In no way would I slight what you have done, you are a true developer and that is very much appreciated. All of this is why I have my GitHub as private with only a few - you, Richie, and Sigi as collaborators, really I do not want a copy of anything I try to work with out there,I prefer that someone if possible might refine some of the things I try to be of use possibly. Sigi is there because I added a keyboard function for vfoa and vfob tx swap that he asked help with. If I am off base I sincerely apologize. 

73’s
Joe
WD5Y

**Comment by sjk7** [comment]
Hi Joe,

Not at all, you have done nothing wrong. I don't know why you think I would
be mad at you ;-)
Maybe it is the language barrier! LOL.

No, you carry on doing what you are doing. I was actually trying to
encourage you, not to admonish you!

The main thing is that coding is fun and Github is a great educational aid;
I really meant what I said; I was not being sarcastic.
You, my friend, are using Github in it's true spirit, so don't worry, ok :-)

Steve

**Comment by WD5Y** [comment]
Thanks, I’m sorry. To explain, I did have my GitHub public a while back and some copies got out there and caused confusion, I really felt bad about it. I do a lot of copying and pasting with Thetis and that’s about as far away from a code developer as you can get. I believe people do not really understand the thought and head scratching that you go through with developing code, I just read some of the lines and am blown away by it. A lot of times we become arm-chair quarterbacks, we think we know and understand but not really. Anyway, the last thing I want to do is confuse things further. For you to be contributing to all of this when really it should be paid for is so much appreciated. 

Thanks and 73’s
Joe
WD5Y

**Comment by sjk7** [comment]
Oh! I see the misunderstanding here!

You thought I meant, "take other people's work and pass it off as your own"
-- plagiarism!
No, no , no, this is not what I meant at all. I was not being sarcastic
like this

As I said, this is what GH is for -- take the code, make it do _exactly_
what you want. There, is that better?

Non-verbal comms can be a pain in the ass sometimes, but you should know my
comment came from a good place.

Steve

**Comment by WD5Y** [comment]
I understand, really. Again, thanks for the encouragement very much and I’m very sorry for taking that the wrong way. 

Thanks,
Joe
WD5Y
