### ISSUE TITLE
[BUG] Thetis.exe remains open after closing main program

### ISSUE THREAD

**Issue by RdWing** [sjk7/Thetis-2.9.0#49]
Thetis x64, Latest version through probably v21.
Windows 11 Pro
7000 DLE MK2.5

In the past week or so I have noticed occasionally that Thetis.exe is remaining open even after Powering Off the radio, and closing Thetis via the X in the top right corner. All Thetis windows appear closed, but Thetis.exe process is continuing to run.

This is occuring fairly regularly, mostly noticed when closing Thetis then trying to install a new version, but it's happening during regular operation too.

I haven't yet discovered exactly what is causing it. The process doesn't appear to be hung and can be killed via Task Manager without issue.

I have taken a [dump of the process](https://devsecopsit-my.sharepoint.com/:u:/p/jon/EVsIElfouIJFtd0Incm1LRABzMV8PSR1SbZTsfZk8RS0EA?e=rLrqzF), but beware it is a large file (1 GB).

Also have seen this:
![image](https://user-images.githubusercontent.com/19214916/235383373-3e83ee5e-3c18-4e33-9ba7-daf27a98dddb.png)

**Comment by sjk7** [comment]
Could be related to the recent form ownership changes. I saw this when I first owned setup correctly. It would only hang in an inifinite loop @ shutdown when 'auto save' was turned on. Quite bizarre.

**Comment by sjk7** [comment]
Bloody thing! I found that if I type something like "hopefully close #19" in my commit, it auto-closes the issue. Let me manually reopen this so I can get feedback on the next revision release,
Steve

**Comment by sjk7** [comment]
Well, I use the word "destruction", but in C# there is no such thing. But you know what I mean, meh.

**Comment by sjk7** [comment]
Hello,

Haven't seen this for ages whilst working on the "puresignal" bug, so will close for now. Can always reopen later, but I strongly suspect this one has gone away in my current working branch,

Steve
