### ISSUE TITLE
[BUG] FFT Bin Width for TX shows 0.000 Hz

### ISSUE THREAD

**Issue by NC3Z** [sjk7/Thetis-2.9.0#50]
**Describe the bug**
The FFT Bin Width for TX shows 0.000 (Settings > Display > TX > FFT), however the slider holds correctly. You can change and the Bin Hz display updates but reverts back to showing 0.000 upon a restart.

**To Reproduce**
Steps to reproduce the behaviour:
1. Settings > Display > TX > FFT
2. Check Bin width to see if it is 0.000
3. You can change it and it seems fine
4. Upon restarting Thetis it shows 0.000

**Expected behaviour**
Hz display should hold upon restart

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 11

![Screenshot 2023-04-30 203857](https://user-images.githubusercontent.com/34176039/235384323-06b60f42-14c8-4c2e-b885-92f3a3b4f0a9.jpg)

**Comment by RdWing** [comment]
Yeah, I've noticed this one for awhile. Good catch.

**Comment by sjk7** [comment]
Thanks, well pointed out with the picture. It is squashed in a forthcoming revision
Steve
