### ISSUE TITLE
[BUG] .29 will not start and gives DirectX error

### ISSUE THREAD

**Issue by NC3Z** [sjk7/Thetis-2.9.0#52]
**Describe the bug**
Launching .29 produces two DirectX popup error - see screenshots:

![Error 1](https://user-images.githubusercontent.com/34176039/235777037-1a54bdbc-1f7c-4f14-bd06-ee749c47139a.jpg)

![Error 2](https://user-images.githubusercontent.com/34176039/235777041-f0c49624-e4f4-414d-a86f-dc842f41b327.jpg)
 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install .29 and launch

**Desktop (please complete the following information):**
 - OS: Win 11Pro 22H2

**Additional context**
Uninstalled .29 and installed .27 and no issues.

**Comment by oldjackbob** [comment]
I'm seeing the same thing.

Mark

**Comment by sjk7** [comment]
Mark are you also on win 11?

Thanks
Steve

**Comment by sjk7** [comment]
I do have win11 here but it is on ARM. I can try it, and hopefully it will fail
Steve

**Comment by oldjackbob** [comment]
> Mark are you also on win 11?
> 
> Thanks Steve

Yes sir, Win11 Home **Beta** (OS Build 22624.1680).

Mark

**Comment by NC3Z** [comment]
So I installed .29 on a lesser PC that runs Windows 10 Pro and it runs fine. This PC is a i7-6500U with the native Intel HD Graphics 520. 3840x2160 resolution and 4K monitor.

The W11 Pro PC that fails is a i7-10700 with native Intel UHD Graphics 630. 3840x2160 resolution and 4K monitor.

**Comment by sjk7** [comment]
Interesting. Thanks! I found that it also runs fine on 'doze 11 ARM64. Did you by any chance try the ol' database reset check? ie delete (rename) your db first?

Steve

**Comment by NC3Z** [comment]
No, but will give that a shot.

**Comment by oldjackbob** [comment]
Thetis does start up fine if I delete the database first. But when I Import the latest database and restart, it gives me the errors noted in the OP and does not start.

Mark

**Comment by nj2us** [comment]
Just another data point: Intel i9-10900K Win 11 Pro 22H2 Nvidia GTX 2060 2.9.0.29
No Direct X errors, no other anomolies so far.,

73,
NJ2US

**Comment by NC3Z** [comment]
Deleting the DB does allow it to now start.

**Comment by RdWing** [comment]
No errors here, Windows 11 Pro, Ryzen 9 5900x, NVidia 3080.

**Comment by NC3Z** [comment]
OK, deleted the db and painstakingly reconfigured the settings by hand. Did a little bit at a time to see if I could find the snag point. All was going well and then I started .29 again dang if the DirectX error didnt pop back up.

**Comment by sjk7** [comment]
ok, useful feedback. I did wonder because I used it extensively last night for a 1:1 qso on 60m, and it was good, though I need to check the band stacks. @RdWing 

@NC3Z Can you help out? Can you make it fail again if you use _that_ database, and, if so, please attach it.

@oldjackbob Please attach your database, and hopefully it will fail here.

Thanks guys,

Steve

**Comment by sjk7** [comment]
> OK, deleted the db and painstakingly reconfigured the settings by hand. Did a little bit at a time to see if I could find the snag point. All was going well and then I started .29 again dang if the DirectX error didnt pop back up.

Thanks for going to all that trouble. Please attach the database that gives you the trouble, and I will see if I can then replicate,

Steve

**Comment by sjk7** [comment]
@RdWing Same thing regarding the bandstacks. Please attach your db for that one, also

Steve

**Comment by NC3Z** [comment]
The painstaking part was making small changes and restarting to find a failure point, but it waited until I was all done and then decided to do it again. Going back to .27 works fine, even using the .29 DB with .27. Happy to test regardless.

Attached are 2 DB's, one from .27 and one from .29 that now fails.

[database.zip](https://github.com/sjk7/Thetis-2.9.0/files/11389647/database.zip)

**Comment by sjk7** [comment]
> The painstaking part was making small changes and restarting to find a failure point, but it waited until I was all done and then decided to do it again. Going back to .27 works fine, even using the .29 DB with .27. Happy to test regardless.
> 
> Attached are 2 DB's, one from .27 and one from .29 that now fails.
> 
> [database.zip](https://github.com/sjk7/Thetis-2.9.0/files/11389647/database.zip)

Yes, that's why I am grateful -- doing stuff like this canbe a pain in the ass!

Steve

**Comment by torrenthd** [comment]
Windows 11 Education 22H2 (22621.1635)
Ryzen 7 3700X
Ati Radeon R9 280X

No issues at all.

**Comment by oldjackbob** [comment]
> @oldjackbob Please attach your database, and hopefully it will fail here.
> 
> Thanks guys,
> 
> Steve

Very sorry Steve, I just got home, here's my database (saved tonight from 2.9.0.27):

[Thetis_database_export_5-3-2023_8.03 PM.zip](https://github.com/sjk7/Thetis-2.9.0/files/11392248/Thetis_database_export_5-3-2023_8.03.PM.zip)


Mark

**Comment by sjk7** [comment]
No worries. It's fixed in source, I have not built the installer yet.

Steve
