### ISSUE TITLE
0Hz signal

### ISSUE THREAD

**Issue by mdblack98** [sjk7/Thetis-2.9.0#53]
I'm seeing a rather large 0Hz frequency -- and there is no such thing.
I think what's happening is the 0th element of the FFT is being  used and that is the DC offset.

Mike W9MDB
![Screenshot 2023-05-03 102718](https://user-images.githubusercontent.com/8899915/235993790-cb5fe47b-4831-4679-85c1-bf5c6681c9fa.jpg)

**Comment by mdblack98** [comment]
I don't think this is new behavior -- there's a new local noise source I was trying to chase down and noticed this when looking at the low frequency info.

This fixes the wide band display
diff --git a/Project Files/Source/Console/wbDisplay.cs b/Project Files/Source/Console/wbDisplay.cs
index 32947b3..93c0499 100644
--- a/Project Files/Source/Console/wbDisplay.cs
+++ b/Project Files/Source/Console/wbDisplay.cs
@@ -2354,7 +2354,7 @@ namespace Thetis

             try
             {
-                Parallel.For(0, W,
+                Parallel.For(1, W,^M
                     (i) => // for(int i = 0; i < W; i++)
                     {
                         float max = float.MinValue;

**Comment by sjk7** [comment]
Thanks for the code. It is in the repo now,

Steve

**Comment by mdblack98** [comment]
That patch fixes the WB view but does not fix the Panadapter.
I'm trying to figure out where the FFT is being done for that.

**Comment by mdblack98** [comment]
Need to re-open this -- it is still a problem in the panadapter.

**Comment by sjk7** [comment]
Hello,

You can't find the code for me, like b4 ;-)

Steve

**Comment by sjk7** [comment]
Yep, no worries, can reopen. Always happy to do that, especially when a commit comment auto-closes the thing!

Cheers,
Steve

**Comment by sjk7** [comment]
I want to close this for now, as it may well go away when I add a ton of changes from another branch. Feel free to re-open at a later date if this still troubles you.

Steve
