### ISSUE TITLE
HL-2 Watt meter reading low.

### ISSUE THREAD

**Issue by WA4SIX** [sjk7/Thetis-2.9.0#55]
**Describe the bug**
With 2 month old HL-2, your version of Thetis shows 70mw output. I have tried Apollo & Alex settings & both showed in the 70W rangeAll 3 as read in Thetis. On the X.X.X.6 version with HL-3 patch, I was reading 5.5W.

My watt meter is not "Calibrated", but I get 5.5W PEP on Thetis & 6W PEP on SDR-Console.

I am wondering if I have missed a setting or need to import settings to get the readings proper. I tried tinkering with the Watt Meter settings, but was not getting any results.

If you need screenshots of anything, please inform me how to do it.

Dell WIN10 Pro laptop

Thank you,
Ed
Wa4SIX

**Comment by WA4SIX** [comment]
I forgot to mention that this is the .29 version.

Thank you,
Ed
WA4SIX

**Comment by WA4SIX** [comment]
OK, after doing some playing around with the Watt meter settings in Tune mode. 
In Apollo mode, 20W to 100W are at 100 for a setting. 10W is at 120.4 Tune slider seems linear & matches the watt meter at 7W in Tune mode. I "Applied" & "Saved". 
Shut down Thetis & restarted. Settings stayed. 
In PA Values, PA Fwd Power, it still shows 83.8W in Tune mode.
Seems Tune, TOne & MOX are all reading similar to my watt meter now.
Not sure if this is actually a bug, or something I should have set myself. If so, sorry for wasting your valuable time.

Thank you,
Ed
WA4SIX

**Comment by sjk7** [comment]
Hello,

There are some upcoming changes, or perhaps merges, from Reid (mi0bot) that will fix this. For me, what I did with my HL2 was to set the power to read x10 of the actual power for now.

Steve

**Comment by WA4SIX** [comment]
Excellent. Thank you for all of your hard work.
Ed
    On Friday, May 12, 2023 at 06:17:52 PM EDT, sjk7 ***@***.***> wrote:  
 
 


Hello,

There are some upcoming changes, or perhaps merges, from Reid (mi0bot) that will fix this. For me, what I did with my HL2 was to set the power to read x10 of the actual power for now.

Steve
