### ISSUE TITLE
Latest Installers on 15 April 2023 are both 32 bit [BUG]

### ISSUE THREAD

**Issue by jeffreydoran** [sjk7/Thetis-2.9.0#6]
* No 64 bit Installer found at 15Z 15 April 2023 
* the x64 file loads the 32 bit version

**Comment by W1AEX** [comment]
Confirming what Jeff has reported.   de Rob W1AEX

**Comment by sjk7** [comment]
Bugger! Will fix. Thanks! How is the 32-bit world? ;-)

**Comment by W1AEX** [comment]
LOL, we are quite grateful for all kinds of code! Thanks Steve. de W1AEX

**Comment by sjk7** [comment]
Thanks guys. This is a weird but old problem with the installer, I see. It is WIX. I _hate_ it, and if I could I would replace it with InnoSetup. It is on a long list of things for the future. Latest installers are working for 32 and 64 bit. I have checked it out, seems OK to me -- now. Ta!

Steve
