### ISSUE TITLE
Shall I continue to build the 32-bit version?

### ISSUE THREAD

**Issue by sjk7** [sjk7/Thetis-2.9.0#7]
**Is your feature request related to a problem? Please describe.**
Does anyone actually use the 32-bit version?

**Describe the solution you'd like**
If no, I will not continue to build and upload it in Releases

**Describe alternatives you've considered**
Maybe leave as-is, but less effort is always easier!

**Additional context**
Don't want to leave 32-bit users out in the cold.

**Comment by jeffreydoran** [comment]
No, I hunt for 64 bit applications wherever possible, and avoid 32 bit apps where ever possible.
Jeff NJ2US

**Comment by DH1KLM** [comment]
I think there's nothing wrong with releasing a 32-bit version.
Even though the majority of OMs prefer the 64-bit version, there are still some that use a 32-bit version.

**Comment by RdWing** [comment]
I don't see any reason to release x32 versions in the future.

**Comment by oldjackbob** [comment]
I don't see a need. I don't even think Richie is building 32-bit versions of his stuff anymore.

**Comment by sjk7** [comment]
@oldjackbob Thanks for feedback. I pretty much have stopped building the 32-bit release. No-one has complained so far. But, you know, hey, the internet! LOL :-)
