### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kingsqueak** [sjk7/Thetis-2.9.0#8]
Win 11 pro x64 current patch level

Anan 7000 mkII DLE black face

Run the latest package as of right now the Thetis.zip that is linked.

Did Add/Remove Programs uninstall prior

Upon startup, portaudio.dll and I think it was SuperCool.dll are missing so the app doesn't start.

I suspect a few .dll's were missing in the packaged installer.

App doesn't run.

Reverting to the 2.9.0.11 it runs again.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows7/8.1/10/11/etc]

**Additional context**

**Comment by kingsqueak** [comment]
I had the wrong file...

**Comment by sjk7** [comment]
No worries. Yes, you want the msi package, either 64 or 32 -bit. The zip file is source and won't run without a development environment installed (I use Visual Studio 2022 for that).

Still, appreciate you took the time to report it, as it may help others if they do the same thing.

Steve

**Comment by kingsqueak** [comment]
Thank you for the work you're doing.

With 2.9.0.15 it seems to be running fine, updated from .11

I'm all VAC here on the 7000 DLE mkII, the original black face.
