### ISSUE TITLE
PureSignal 2.0 doesnt initialize to same  Default SetPk value in .8 vs .15[BUG]

### ISSUE THREAD

**Issue by jeffreydoran** [sjk7/Thetis-2.9.0#9]
I Noticed that Pure Signal correction seemed a bit out of alignment while using 2.9.0.15. Not getting the traditional "propeller" trace in AmpView.
Clicking Default under the Advanced Tab of Linearity -> Advanced should populate SetPk field to 0.2899 (on my radio) as this is what happens when you click Default in Linearity->Advanced in Thetis 2.9.0.8

Clicking Default in 2.9.0.15 sets SetPk to 0.2432906

These numbers are arbitrary and probably related to individual radios, firmware, etc. My point is that for the same given radio, same firmware, I would expect the SetPk value would calculate out to the same value, regardless of revision. Maybe, maybe not.

This causes pure signal not to replicate what we see in 2.9.0.8, and behaves differently.
Manuallly resetting SetPk to 0.2899 (on my radfio) corrects the issue, and Pure Signal works as expected.

Disclaimer: Im not a guru in this area, and this is just an observation as I practice with 2.9.0.15
My observation of the propeller trace in ampview is what other users usually report when they believe that Pure Signal is operating normally in 2.9.0.8. In 2.9.0.15, the ampview trace appears as a cigar. I cant say this is bad,  but my attention was called to it because I was seeing a higher level of IMD in 2.9.0.15

Jeff NJ2US

**Comment by RdWing** [comment]
The ampview "view" really has little to do with it. Different values are required for P1 vs P2 for SetPk. I think that's all.

**Comment by jeffreydoran** [comment]
You misunderstood my report. I'm seeing increased IMD in a trap view compared to 2.9.0.8

**Comment by RdWing** [comment]
That is understood, but the unexpected behavior is that the Default button in the PureSignal window sets SetPk to some unexpected value for the type of radio you're using. The correct value of SetPk varies for different radios and for P1 v. P2.

**Comment by jeffreydoran** [comment]
Thank you. My point is that Pure Signal is not performing as well under .15 compared to .8, and I'm using the same radio with P2 with both revisions.

**Comment by jeffreydoran** [comment]
From MW0LGE:
protocol 1 = 0.4072
protocol 2 = 0.2899

the default button will always assign one of those two values. If you adjust it, the adjusted value will be used next time. I do need to reset it if protocol is changed in setup (to do).

NJ2US

**Comment by sjk7** [comment]
Heh. Let me add to this one. I didn't know it was 0.2899 in P2.
So the full list should be:

Protocol 1 = 0.4072 (unless it is HL2, then it is 0.2xxxx (I forget))
P2             =  0.2899
I just thought it was 0.4072 for everything other than HL2.

So, thanks to your info, I can put that right.

Here's the important thing: What should happen is once you set that number to anything you want, it should stick.
However, it is very much like the radio sample rate list, in that if the protocol changes when you connect (for example if you select the wrong one before you connect), it's likely gonna go the default.

While it is busted: can you check to see if the value you type in that field (for, you, 0.4072) is remembered (assuming P2 is set for all scenarios so it does not change when you connect).

Thanks! G7KLJ

**Comment by jeffreydoran** [comment]
For me, on Protocol 2, the SetPk is 0.2899, and once I manually enter it into the SetPk field, it "sticks" to the database. 

Thanks Steve, great job with Thetis. 

NJ2US

**Comment by NC3Z** [comment]
What Jeff said, once set to the proper value it does stay put.
